 platform :ios, ‘9.0’

target 'Snatch' do
  use_frameworks!

  pod “AFNetworking”, '~> 3.1.0’
  pod “SDWebImage”
  pod “MBProgressHUD”
  pod “MJRefresh”, ’~> 3.1.12’
  pod “JSONModel"
  pod “Masonry”
  pod “MJExtension”
  pod “SVProgressHUD”
  pod “YYKit”
  pod “UMengAnalytics” 
  pod “WebViewJavascriptBridge”, '~> 5.0'
  pod “FMDB”

  end

